---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: kairos-capi-system
      path: /mutate-bootstrap-cluster-x-k8s-io-v1beta2-kairosconfig
  failurePolicy: Fail
  name: mkairosconfig.kb.io
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - kairosconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: kairos-capi-system
      path: /mutate-controlplane-cluster-x-k8s-io-v1beta2-kairoscontrolplane
  failurePolicy: Fail
  name: mkairoscontrolplane.kb.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - kairoscontrolplanes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: kairos-capi-system
      path: /validate-bootstrap-cluster-x-k8s-io-v1beta2-kairosconfig
  failurePolicy: Fail
  name: vkairosconfig.kb.io
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - kairosconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: kairos-capi-system
      path: /validate-controlplane-cluster-x-k8s-io-v1beta2-kairoscontrolplane
  failurePolicy: Fail
  name: vkairoscontrolplane.kb.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - kairoscontrolplanes
  sideEffects: None
