resources:
- bases/bootstrap.cluster.x-k8s.io_kairosconfigs.yaml
- bases/bootstrap.cluster.x-k8s.io_kairosconfigtemplates.yaml
- bases/controlplane.cluster.x-k8s.io_kairoscontrolplanes.yaml
- bases/controlplane.cluster.x-k8s.io_kairoscontrolplanetemplates.yaml

