# clusterctl metadata.yaml
# This file is used by clusterctl to discover and install the provider
# It should be published alongside the components.yaml in releases

apiVersion: clusterctl.cluster.x-k8s.io/v1beta1
kind: Metadata
releaseSeries:
  - major: 0
    minor: 1
    patches:
      - version: v0.1.0
        releaseDate: "2024-11-21"
        url: https://github.com/wrkode/kairos-capi/releases/download/v0.1.0/components.yaml
        contract: v1beta2
        files:
          - url: https://github.com/wrkode/kairos-capi/releases/download/v0.1.0/components.yaml
            sha256: "" # TODO: Add SHA256 checksum
          - url: https://github.com/wrkode/kairos-capi/releases/download/v0.1.0/metadata.yaml
            sha256: "" # TODO: Add SHA256 checksum

